--- 

- name: Ensure nginx service is stopped on Ubuntu 22.04 

  hosts: localhost 

  connection: local 

  become: true 

 

  tasks: 

    - name: Ensure nginx service is stopped 

      ansible.builtin.service: 

        name: nginx 

        state: stopped 