---
- name: Install Nginx
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: true

    - name: Install nginx
      apt:
        name: nginx
        state: present