---
- name: Ensure the unzip package is installed
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: true

    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present