---
- name: Ensure the nginx service is started
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started